heat conversion, method movement comparisons, methodClassBacking, kee…
googleinterns/kevin-grosman-2020 pull request #21
Opened 2020-08-07 01:38 UTC by kgrosman

…p, back, stability

2020-08-10 23:44 UTC, diablonhn requested changes
Pull request needs a better name and description.

2020-08-10 23:44 UTC, diablonhn commented on CUJExecutor/back
> +# INPUT: a .prof file followed by any number of tags in {HSPL, HPL, PL}
Technically, the tags are:

  - H
  - S
  - P

A method in the profile can be prefixed with any or all of them, in any order.  But it's okay (though not safe) to assume that the tags only come together as `HSPL`, `HPL`, or `PL`.

`L` is not a flag and it is the start of a Java class signature that ends with `;`.

2020-08-10 23:44 UTC, diablonhn commented on CUJExecutor/back
> +#!/usr/bin/env bash
The file `back` needs a more descriptive name.

2020-08-10 23:44 UTC, diablonhn commented on CUJExecutor/buildProfile
> +STASHING_MPT_INFO="/tmp/manipulate_info.txt" #Contains the actions used to compile, in case callee wants it
Should just use the unshortened name `STASHING_MANIPULATE_INFO`.

2020-08-10 23:44 UTC, diablonhn commented on CUJExecutor/buildProfile
> +		cat "/tmp/tmp.txt" > $CREATED_PROFILE
Can this use `cp` instead?

2020-08-10 23:44 UTC, diablonhn commented on CUJExecutor/churn
> +PROFILE=${1?"ERROR:NEED TO PROVIDFE A PROFILE"}
Typo `PROVIDFE`.

2020-08-10 23:44 UTC, diablonhn commented on CUJExecutor/churn
> +#!/usr/bin/env bash
Name `churn` isn't too clear what the file is doing - needs a better name.

2020-08-10 23:44 UTC, diablonhn commented on CUJExecutor/churn
> +adb pull /data/misc/profiles/ref/com.google.android.apps.maps/primary.prof $CHURNED_PROFILE 2>&1 >/dev/null
Optional: support other apps besides `com.google.android.apps.maps`.

2020-08-10 23:44 UTC, diablonhn commented on CUJExecutor/compileWith
> +#!/usr/bin/env bash
`compileWithProfile` is probably a better name than `compileWith`.

2020-08-10 23:44 UTC, diablonhn commented on CUJExecutor/convert
> +#Prints out a version of this profile where all dump entries with the tag $FROM are switched to having the tag $TO
Change `dump` to `profman classes-and-methods dump`?

2020-08-10 23:44 UTC, diablonhn commented on CUJExecutor/convertToH
> +#!/usr/bin/env bash
Spell out `convertToH` to `convertToHot`?

2020-08-10 23:44 UTC, diablonhn commented on CUJExecutor/fileToDump
> +# If a .txt file is passed, it is enterpretted as the dump to be returned.
Typo `enterpretted`?  Instead of interpretted, the file is simply passed through.

2020-08-10 23:44 UTC, diablonhn commented on CUJExecutor/keep
> +#!/usr/bin/env bash
Needs a better descriptive name than just `keep`.

2020-08-10 23:44 UTC, diablonhn commented on CUJExecutor/methodClassBacking
> +#If we are provided a profile, convert it to it's dump. If we were given a text file, interpret it as the dump
`it's` -> `its`

2020-08-10 23:44 UTC, diablonhn commented on CUJExecutor/methodClassBacking
> +#!/usr/bin/env bash
`methodClassBacking` -> `addMethodClassToProfile`?

2020-08-10 23:44 UTC, diablonhn commented on CUJExecutor/stableProfile
> +# OUTPUT: a message saying whether the profile is stable.
What is the definition of a stable profile?

2020-08-12 17:48 UTC, kgrosman commented on CUJExecutor/back
> +# INPUT: a .prof file followed by any number of tags in {HSPL, HPL, PL}
Hmmm from what I understand, you could have any of these tags, but when you convert from a profile to a dump, they are always in the order H -> S -> P -> L and I've never seen a ref profile have any combinations other than HSPL, HPL, or PL. Is this accurate to your knowledge?

2020-08-12 17:48 UTC, kgrosman commented on CUJExecutor/stableProfile
> +# OUTPUT: a message saying whether the profile is stable.
definition on line 5 :P

2020-08-12 18:06 UTC, diablonhn commented on CUJExecutor/back
> +# INPUT: a .prof file followed by any number of tags in {HSPL, HPL, PL}
It makes sense for ART to only save certain tags to the profile, hence the lack of other combinations.

2020-08-20 19:43 UTC, diablonhn requested changes
There are a lot of scripTestFiles.  Is that intended?

2020-08-20 21:07 UTC, kgrosman commented
> There are a lot of scripTestFiles. Is that intended?

Yeah, the test files were modified to be a little more nuanced (since I made a change to the way prof intersections/unions worked)

2020-08-20 21:38 UTC, diablonhn approved these changes

2020-08-20 22:40 UTC, merged